travis:
  secure:
    BINSTAR_TOKEN: iLCKnt6cb414LuTmyBgyKp4FrUT1s9vSl5k7KFiLd6U8W/sOtzSM3ebxvO9CT4ulHQNWIk56kuFQsrJISddQAYlyxMq7++Nv5ZQJnHyUtA/I9yqWKX5Xu3D5TjSXj3Y+ku3ZsEkrDxBBNvHU3UNzEykvlg7nrYtBXUmTLzvJ7KiKCT2VcwLz7b1IM+xdDhLpxgYk6pHeeKWOwURO6+oqVnJLMZmI+DdHYqE/lkQR/h25ctEtSXBu8PRVoTH2ihXqK3yIkoVE+jQzy8pFIxueWQlKkmw3xsYPCQU8IkH8BjqqcRENLijiGjFERaxPWuY6I44M5BkLo0j2CBcTnv9fRkcJ0jMU7GBBiSN+qhvXEc2bzysV3x2f9rsl+2ugRYyybnFuFMoEEXUqU/k94ZSSb0I5ObSKcwV9MlHN8ohWYXxv7lYbMH1MgHRvogQCKvsH4a6469hhBhCMSPu+kcfyVNZB16JggRhs+h03Nnk92mE0n2qhSoc3tjLroiENzICX+D+8jbUZ8v3ueJx19l91etEwZQ9mpa/j30bYrLe41jDqosxUPPVpYBRObQ8altjVP07EJSdiU0ObN6VvLxYWFZv3V5kgUbc/8Umm25zFwPdgarWHUsajql0tq1LIr2o3sYjS3iWR1XNT4oLyiYdXg/salewOGKonKMxps1C2vEw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
